# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hamilton Mendes
email: hamilton_j[arroba]gmx.com
description: > # this means to ignore newlines until "baseurl:"
  “Fear doesn't go away. The warrior and the artist live by the same code of necessity, which dictates that the battle must be fought anew every day.” ― Steven Pressfield
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hamilton-m.github.io" # the base hostname & protocol for your site
urlttps: "https://hamilton-m.github.io" # the base hostname & protocol for your site
twitter_username: null
github_username:  null
google_analytics: G-T70L3399E2

# Build settings
markdown: kramdown

plugins:
  - jemoji
  - jekyll-redirect-from
  
whitelist:
  - jekyll-redirect-from
  
#emoji:
#  src: "/assets/images/emoji"
